fix boost-context detection
i'm not sure this fix is accurate, but it fixes detection failure

configure:18038: x86_64-pld-linux-g++ -c -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -O2 -fwrapv -pipe -Wformat -Werror=format-security -gdwarf-4 -fno-debug-types-section -fvar-tracking-assignments -g2 -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIC -march=x86-64 -gdwarf-4 -fno-debug-types-section -fvar-tracking-assignments -g2   -I/usr/include conftest.cpp >&5
conftest.cpp: In function 'int main()':
conftest.cpp:32:71: error: invalid conversion from 'boost::context::fcontext_t {aka void*}' to 'void**' [-fpermissive]
 boost::context::fcontext_t* fc = boost::context::make_fcontext(0, 0, 0);
                                                                       ^
conftest.cpp:32:29: warning: unused variable 'fc' [-Wunused-variable]
 boost::context::fcontext_t* fc = boost::context::make_fcontext(0, 0, 0);
                             ^
configure:18038: $? = 1
configure: failed program was:
| #include <boost/context/all.hpp>
| int
| main ()
| {
| boost::context::fcontext_t* fc = boost::context::make_fcontext(0, 0, 0);

autoconf-archive seems to have same code as mcrouter's copy
http://www.gnu.org/software/autoconf-archive/ax_boost_context.html#ax_boost_context